export default {
  bespin: require('./bespin.png'),
  coruscant: require('./coruscant.png'),
  dagobah: require('./dagobah.png'),
  endor: require('./endor.png'),
  geonosis: require('./geonosis.png'),
  hoth: require('./hoth.png'),
  kamino: require('./kamino.png'),
  alderaan: require('./alderaan.png'),
  tatooine: require('./tatoonie.png'),
  naboo: require('./naboo.png'),
  yavin_iv: require('./yavin_iv.png'),
  utapau: require('./utapau.png'),
  mustafar: require('./mustafar.png'),
  kashyyyk: require('./kashyyyk.png'),
  polis_massa: require('./polis_massa.png'),
  mygeeto: require('./mygeeto.png'),
  felucia: require('./felucia.png'),
  cato_neimoidia: require('./cato_neimoidia.png'),
  saleucami: require('./saleucami.png'),
  stewjon: require('./stewjon.png'),
  eriadu: require('./eriadu.png'),
  corellia: require('./corellia.png'),
  rodia: require('./rodia.png'),
  nal_hutta: require('./nal_hutta.png'),
};
